### ISSUE TITLE
Residual computation in 'apply_score'

### ISSUE THREAD

**Issue by jadecci** [katielavigne/score#1]
Hi! I find the SCoRE technique really interesting and was thinking of using it in my project. However, I am confused by one part of the code.

In the `apply_score` function, the regression outcome is subtracted from `parc[r2]`. Should this be `parc[r1]` instead?
https://github.com/katielavigne/score/blob/99f4d004f230c27a9580d53da9ad20996408da7a/apply_score.py#L70

**Comment by katielavigne** [comment]
Hi, you're absolutely right - thank you for finding this! I've updated the code in commit [eb6f14b34625db9df1ff607b659074174426795d](https://github.com/katielavigne/score/commit/eb6f14b34625db9df1ff607b659074174426795d)
